# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache:
  packages: true

warnings_are_errors: true

jdk:
  - oraclejdk8

r_packages:
  - covr

env:
  - SPARK_VERSION="1.6.3"
  - SPARK_VERSION="2.2.1"
  - SPARK_VERSION="2.3.0"

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    if [[ $SPARK_VERSION == "2.3.0" ]]; then
      R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz
      travis_wait 35 Rscript .travis.R --coverage
    else
      travis_wait 30 R CMD check --no-build-vignettes --no-manual sparklyr*tar.gz
    fi

after_failure:
  - |
    grep -B 50 -A 50 ERROR /tmp/sparklyr.log
    cd tests
    export NOT_CRAN=true
    travis_wait 35 Rscript ../.travis.R --testthat
    sleep 2
