baseurl = "/"
languageCode = "en-us"
title = "sparklyr"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
pluralizeListTitles =   "false"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
canonifyurls = true
googleAnalytics = "UA-20375833-13"

contentDir = "blogdown/content"
layoutDir  = "blogdown/layouts"
staticDir  = "blogdown/static"
themesDir  = "blogdown/themes"
publishDir = "blogdown/public"

[params]
    description = "An R interface to Spark"
    copyright = "Copyright 2017, RStudio, Inc."
	  repo = "https://github.com/sparklyr/sparklyr"

[[menu.main]]
    weight = 10
    name = "Using sparklyr"

[[menu.main]]
    weight = 11
    name = "Getting Started"
    parent = "Using sparklyr"
    url = "/guides/connections/"

[[menu.main]]
    weight = 12
    name = "Manipulating data"
    parent = "Using sparklyr"
    url = "/dplyr/"

[[menu.main]]
    weight = 13
    name = "Machine Learning"
    parent = "Using sparklyr"
    url = "/mlib/"

[[menu.main]]
    weight = 14
    name = "Understanding Caching"
    parent = "Using sparklyr"
    url = "/guides/caching/"

[[menu.main]]
    weight = 15
    name = "Deployment Options"
    parent = "Using sparklyr"
    url = "/deployment/"

[[menu.main]]
    weight = 20
    name = "Guides"

[[menu.main]]
    weight = 21
    name = "Distributed R"
    parent = "Guides"
    url = "/guides/distributed-r/"

[[menu.main]]
    weight = 23
    name = "Data Lakes"
    parent = "Guides"
    url = "/guides/data-lakes/"

[[menu.main]]
    weight = 24
    name = "Extend sparklyr"
    parent = "Guides"
    url = "/extensions/"

[[menu.main]]
    weight = 25
    name = "ML Pipelines"
    parent = "Guides"
    url = "/guides/pipelines"

[[menu.main]]
    weight = 26
    name = "Text mining"
    parent = "Guides"
    url = "/guides/textmining"

[[menu.main]]
    weight = 27
    name = "Using H2O"
    parent = "Guides"
    url = "/guides/H2O"

[[menu.main]]
    weight = 50
    name = "Deployment Examples"
    url = "/examples/"

[[menu.main]]
    weight = 51
    name = "Standalone cluster"
    parent = "Deployment Examples"
    url = "/examples/stand-alone-aws/"

[[menu.main]]
    weight = 52
    name = "YARN cluster"
    parent = "Deployment Examples"
    url = "/examples/yarn-cluster-emr/"

[[menu.main]]
    weight = 53
    name = "Cloudera cluster"
    parent = "Deployment Examples"
    url = "/examples/cloudera-aws/"
